FIND_PATH(SFST_INCLUDE_DIR compact.h /usr/include/sfst/ /usr/local/include/sfst/ )

FIND_LIBRARY(SFST_LIBRARY NAMES sfst PATH /usr/lib /usr/local/lib) 

MARK_AS_ADVANCED(SFST_LIBRARY)
MARK_AS_ADVANCED(SFST_INCLUDE_DIR)


IF (SFST_INCLUDE_DIR AND SFST_LIBRARY)
   SET(SFST_FOUND TRUE)
ENDIF (SFST_INCLUDE_DIR AND SFST_LIBRARY)


IF (SFST_FOUND)
   IF (NOT SFST_FIND_QUIETLY)
      MESSAGE(STATUS "Found libsfst: ${SFST_LIBRARY}")
   ENDIF (NOT SFST_FIND_QUIETLY)
ELSE (SFST_FOUND)
   IF (SFST_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find libsfst")
   ELSE (SFST_FIND_REQUIRED)
      MESSAGE(STATUS "libsfst not found")
   ENDIF (SFST_FIND_REQUIRED)
ENDIF (SFST_FOUND)
